name: hearthstone_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.1
  equatable: ^2.0.3
  hooks_riverpod: ^1.0.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  chewie: ^1.2.2
  video_player: ^2.2.7
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/video/
    - .env
    - .env.example
